services:
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      # Config Volume
      - ./.influx/influx-config:/etc/influxdb2:rw 
      # Data Volume
      - ./.influx/influx-data:/var/lib/influxdb2:rw 
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DATABASE_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DATABASE_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DATABASE_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=botdata
    restart: always
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./.grafana:/var/lib/grafana:rw
    restart: always
    #environment:
      #- GF_AUTH_DISABLE_LOGIN_FORM=true

